#+TITLE:  ELISA: An ELISA Plate Reader Application
#+DATE:    December 21, 2019
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
  - [[#hacks][Hacks]]
- [[#roadmap][Roadmap]]
  - [[#detect-the-elisa-plate][Detect the ELISA Plate]]
  - [[#read-vials][Read Vials]]
  - [[#normalize-color][Normalize Color]]
  - [[#feedback][Feedback]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
This application seeks to be the best way to scan ELISA plates and record
measurements.

It's able to scan a plate and record the RGB values of each individual vial
while compensating for differences in lighting and camera.

** Module Flags
This module provides no flags.

** Plugins
{A list of linked plugins}

** Hacks
{A list of internal modifications to included packages}

* Roadmap
** Detect the ELISA Plate
The application should be able to detect the plate without reading from external
sources.
It would be a good idea to show the user taking the photo that the plate has
been detected so as to avoid taking a blurry photo and seeing skewed results.
** Read Vials
The application should be able to take some image of the plate and identify each
of the individual vials on the plate.

It should record the RGB values in some standardized format.
** Normalize Color
The application should (ideally) be able to normalize the color values of the
plate to be able to obtain an accurate reading of the color values.
** Feedback
It would be useful to the researchers to provide an interface through the
application to view normalized pictures of plates and view the RGB readings as
labels of some sort corresponding to each vial through the application.

It would also be useful to store this information in a human-interpretable
table, likely in .csv format, and to be able to back up and/or export this information.
* Configuration
How to configure this module, including common problems and how to address them.

* Troubleshooting
Common issues and their solution, or places to look for help.
